package com.example.scanalot;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.example.scanalot.databinding.ActivityManualEntryBinding;


public class ManualEntryFragment extends Fragment
{
    //here we are using a binding class that is autogenerated when creating a layout file
     private ActivityManualEntryBinding binding;

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
       // Toast.makeText(getActivity(),"This is Manual Entry Scan Fragment On Create",Toast.LENGTH_SHORT).show();
        Log.i("onCreate", "This is the Manual Entry Fragment being created");
    }


    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        /*return super.onCreateView(inflater, container, savedInstanceState);*/
        binding = ActivityManualEntryBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }


}

