package com.example.scanalot;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;

import com.example.scanalot.databinding.ActivityManualEntryBinding;

/**
 * This class is used for the ManualEntryFragment. It creates the fragment and uses the activity_manual_entry layout. This will be used for
 * when user taps the manual entry button and comes to this fragment to manually search for the license plate and determine if it belongs
 * in the designated lot
 *
 * @author Andrew Hoffer
 * @Created 1/22/23
 * @Contributors Andrew Hoffer - 1/22/23 - Created the fragment
 */
public class ManualEntryFragment extends Fragment {
    //here we are using a binding class that is autogenerated when creating a layout file. This allows us to easily access the views.
    private ActivityManualEntryBinding binding;

    /**
     * Method in which executes after the view has been created. It is saving the state of the view
     */
    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
    }

    /**
     * Method in which executes during the creation of the view. It is creating an instance of this fragment
     */
    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        binding = ActivityManualEntryBinding.inflate(inflater, container, false);
        return binding.getRoot();
    }

    /**
     * Cleans up resources when view is destroyed
     */
    @Override
    public void onDestroyView() {
        super.onDestroyView();
        binding = null;
    }
}

